### ISSUE TITLE
Install via composer

### ISSUE THREAD

**Issue by gsfish** [yunify/qingstor-sdk-php#1]
I want to install `yunify/qingstor-sdk` via composer and I get error:

`[InvalidArgumentException]                                                             
  Could not find package yunify/qingstor-sdk at any version for your minimum-stability   
  (stable). Check the package spelling or your minimum-stability`

**Comment by Xuanwo** [comment]
Hi @gsfish , qingstor-sdk-php has not been released since now.
In order to use this beta version, you should specify the version in `composer.json` as follow:

```json
"require": {
  "yunify/qingstor-sdk": "dev-master",
}
```

or

```json
"require": {
  "yunify/qingstor-sdk": "2.0.0-beta.0",
}
```

**Comment by gsfish** [comment]
Thanks. And I found that the require `katzgrau/klogger` also need to be specified in `omposer.json`.

**Comment by Xuanwo** [comment]
Got it
