### ISSUE TITLE
命名冲突

### ISSUE THREAD

**Issue by sunpaolo** [yunify/qingstor-sdk-php#11]
Fatal error: Cannot use GuzzleHttp\Psr7\Request as Request because the name is already in use in XXX/vendor/yunify/qingstor-sdk/src/Builder.php on line 20

**Comment by Xuanwo** [comment]
你好，这是因为在同一个 namespace 下， Request 已经被使用了。

请问这是你自己写的代码么？

**Comment by sunpaolo** [comment]
Builder.php 同级有个 Request.php , 里面又 use GuzzleHttp\Psr7\Request as Request

应该是  use GuzzleHttp\Psr7\Request as PsrRequest吧

**Comment by Xuanwo** [comment]
Fixed in https://github.com/yunify/qingstor-sdk-php/commit/4321857ae2f7e5d7b900c02f451a4e86a64e2023 , thank you for report.
