### ISSUE TITLE
getPolicy() 和 putPolicy() 有一处不合理的地方

### ISSUE THREAD

**Issue by yungkcx** [yunify/qingstor-sdk-php#16]
如果设置了 Bucket 本身的存储空间策略，比如 list_objects。那么 `$res = $bucket->getPolicy()` 之后 `$res->statement[0]['resource']` 为空数组:
```
array(1) {
  [0]=>
  array(5) {
    ["action"]=>
    array(1) {
      [0]=>
      string(12) "list_objects"
    }
    ["effect"]=>
    string(4) "deny"
    ["resource"]=>
    array(0) {
    }
    ["id"]=>
    string(12) "backup-black"
    ["user"]=>
    array(1) {
      [0]=>
      string(1) "*"
    }
  }
}
```
但是，在并没有修改以上 $res 的情况下，执行`$bucket->putPolicy(array('statement' => $res->statement))` 时却：
```
PHP Fatal error:  Uncaught QingStor\SDK\Exception\ParameterRequiredException: [0]: resource is required in statement.
  thrown in /var/www/html/vendor/yunify/qingstor-sdk/src/QingStor/Bucket.php on line 1766
```
这里除非手动修改 get 到的 policy，否则没有办法用该 policy 进行新的设置，给 SDK 的使用造成了一定麻烦。

**Comment by pengsrc** [comment]
这个应该是 API Specs 有误，会修改一下 Specs，然后重新生成 SDK，具体参考这里 https://github.com/yunify/qingstor-api-specs/blob/master/2016-01-06/swagger/bucket_policy.json#L37-L39

**Comment by pengsrc** [comment]
QingStor API Specs 已修复该问题，各 SDK 会稍后更新，https://github.com/yunify/qingstor-api-specs/commit/08498b47e1702d1b6de9b198e3a55227e8ed4c86

感谢反馈

**Comment by Xuanwo** [comment]
Confirmed, I will update the sdk.
