### ISSUE TITLE
Bugs in documentation

### ISSUE THREAD

**Issue by gsfish** [yunify/qingstor-sdk-php#2]
`README.md` missed ";" in line 44, 48 which may raise syntax error.
`docs/installation.md` should change "npm" into "composer" in line 5.

**Comment by Xuanwo** [comment]
Got it, I will fix it tomorrow.
Thank you for your report.

**Comment by gsfish** [comment]
`docs/qingstor_service_usage.md` missed `;` in line 36, 42.
`acl` miss the right quote in line 56.
And `bucket` should be change into `$test_bucket` in line 42.

**Comment by Xuanwo** [comment]
Got it.
And please open a new issue instead of replying in an already closed issue.

**Comment by gsfish** [comment]
OK
