### ISSUE TITLE
php7.0 签名异常

### ISSUE THREAD

**Issue by yuebin1009** [yunify/qingstor-sdk-php#26]
count(): Parameter must be an array or an object that implements Countable {"exception":"[object] (ErrorException(code: 0): count(): Parameter must be an array or an object that implements Countable at /Users/yuebin/PhpstormProjects/code/php/invoice/vendor/yunify/qingstor-sdk/src/Builder.php:138)

Bucket.getObjectRequest 第三个参数$options = []

**Comment by Xuanwo** [comment]
Fixed with https://github.com/yunify/qingstor-sdk-php/commit/a2281450733d22abbc413dd3f48581dfd299ecbc merged.
