### ISSUE TITLE
Using Content-MD5

### ISSUE THREAD

**Issue by gsfish** [yunify/qingstor-sdk-php#3]
I set a `Content-MD5` value which has no relation to the content in request header when I use `putObject`, but still can get 201 code in response.

```
$res = $test_bucket->putObject(
    "test_object_key.jpg",
    array(
        "body" => file_get_contents("/home/gsfish/Pictures/37781215_p0.jpg"),
        "Content-Type" => "image/jpeg",
        "Content-MD5" => base64_encode(md5("aaa", true))
    )
);
echo $res->getStatusCode() . "\n";
```

**Comment by Xuanwo** [comment]
While body is set, SDK will calculate Content-MD5 automatically, and override user's input.
https://github.com/yunify/qingstor-sdk-php/blob/master/src/Builder/Base.php#L83-L86

**Comment by prettyxw** [comment]
>> SDK will calculate Content-MD5 automatically, and override user's input

It's not appropriate and necessary to calculate MD5 of each object. The upload process may be slowed down by doing extra calculating.

**Comment by Xuanwo** [comment]
Fixed.
